template_path: templates/edge-lambda.yaml
parameters:
  Environment: {{ environment_path.0 }}
  Project: {{ environment_config.project_code }}
stack_tags:
  Environment: {{ environment_path.0 }}
  Project: {{ environment_config.project_code }}
