template_path: stacks/cloudfront.yaml
parameters:
  Environment: {{ environment_path.0 }}
  Project: {{ environment_config.project_code }}
  Domain: staging.teemukoivisto.xyz
  DNSStackName: gatsby-blog-staging-dns
  BucketStaticDomainName: teemukoivisto.xyz.s3-website.eu-central-1.amazonaws.com
  AcmCertArn: arn:aws:acm:us-east-1:626386600593:certificate/df030ed3-a41e-4b07-a7a2-ede7f809c187
  EdgeLambdaArn: arn:aws:lambda:us-east-1:626386600593:function:gatsby-blog-staging-edge-lambda-SPAEdgeLambda-EZHV25S7RIJH
  EdgeLambdaVersion: "1" # miksei 3??
stack_tags:
  Environment: {{ environment_path.0 }}
  Project: {{ environment_config.project_code }}
