template_path: stacks/dns.yaml
parameters:
  Environment: {{ environment_path.0 }}
  Project: {{ environment_config.project_code }}
  Domain: staging.teemukoivisto.xyz
stack_tags:
  Environment: {{ environment_path.0 }}
  Project: {{ environment_config.project_code }}
