template_path: dns.yaml
parameters:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
  Domain: teemukoivisto.xyz
stack_tags:
  Environment: {{ command_path.0 }}
  Project: {{ project_code }}
