AWSTemplateFormatVersion: 2010-09-09
Description: Public CloudFront distribution through which _all_ traffic is served and cached (when necessary)

Parameters:
  Project:
    Description: Name of the project
    Type: String
  Environment:
    Description: Environment where the stack is launched
    Type: String
    AllowedValues:
      - staging
      - production
  Domain:
    Description: Domain of the website
    Type: String
  DNSStackName:
    Description: The DNS stack (dns.yaml), full name similar to eg. gatsby-blog-staging-dns
    Type: String
  BucketStaticDomainName:
    Description: Domain of the s3 bucket where the assets lie (eg. HTML/JS of the Gatsby)
    Type: String
  AcmCertArn:
    Description: Certificate arn for cloudfront distribution (needs to be issued in us-east-1 region)
    Type: String
  EdgeLambdaArn:
    Description: Arn of the edge lamba that runs in us-east-1. This will rewrite URLs outside your root to correct s3 URL (it's complicated :D)
    Type: String
  EdgeLambdaVersion:
    Description: Version of the edge lambda
    Type: Number

Resources:
  Distribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub ${Environment} CloudFront distribution for ${Domain} 
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertArn
          SslSupportMethod: sni-only
        Origins:
          - Id: WebsiteStaticAssets
            DomainName: !Ref BucketStaticDomainName
            OriginPath: '*'
            CustomOriginConfig:
              OriginProtocolPolicy: http-only

        Aliases:
          - !Ref Domain
        DefaultCacheBehavior:
          TargetOriginId: WebsiteStaticAssets
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          ViewerProtocolPolicy: allow-all
          DefaultTTL: 120
          LambdaFunctionAssociations:
            - EventType: 'origin-request'
              LambdaFunctionARN: !Sub "${EdgeLambdaArn}:${EdgeLambdaVersion}"
  PublicDNS:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId:
        Fn::ImportValue:
          !Sub ${DNSStackName}-HostedZone-Id
      Comment: !Sub ${Domain} ${Environment} public URL
      Name: !Ref Domain
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt Distribution.DomainName