AWSTemplateFormatVersion: 2010-09-09
Description: A HostedZone for hosting Gatsby website in subdomain eg dev.teemukoivisto.xyz
# Not used in the production environment, since it's more common you have already set up one when you have
# bought a domain.
Parameters:
  Project:
    Description: Name of the project
    Type: String
  Environment:
    Description: Environment where the stack is launched
    Type: String
    AllowedValues:
      - dev
      - prod
  Domain:
    Description: Domain name of the HostedZone eg. app.teemukoivisto.xyz
    Type: String

Resources:
  WebsiteHostedZone:
    Type: AWS::Route53::HostedZone
    DeletionPolicy: Retain
    Properties:
      Name: !Ref Domain
      HostedZoneConfig:
        Comment: The HostedZone for this website
Outputs:
  HostedZoneId:
    Description: The website's HostedZone's id
    Value: !Ref WebsiteHostedZone
    Export:
      Name: !Sub ${AWS::StackName}-HostedZone-Id
  NameServers:
    Value: !Join [",", !GetAtt WebsiteHostedZone.NameServers]
    Export:
      Name: !Sub ${AWS::StackName}-NameServers
  DomainName:
    Value: !Ref Domain
    Export:
      Name: !Sub ${AWS::StackName}-Domain